A reproduction of a PyPy segfault I came across in github actions.

